name: habit_repository
description: Habit repository.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.4

dependencies:
  api_client:
    path: ../api_client
  app_core:
    path: ../app_core
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  rxdart: ^0.28.0

dev_dependencies:
  analyzer: ^5.13.0
  build_runner: ^2.4.13
  isar_generator: ^3.1.0+1
  json_serializable: ^6.7.1
  very_good_analysis: ^6.0.0
